// Audit log action keys
export enum AuditActionKey {
  // Authentication actions
  // Login, logout and credential changes were not traced at all, which left no
  // way to investigate a compromised account (see AUDIT_CODE.md 4.8).
  AUTH_LOGIN_SUCCEEDED = 'AUTH_LOGIN_SUCCEEDED',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_GOOGLE_LOGIN = 'AUTH_GOOGLE_LOGIN',
  AUTH_TOKEN_REFRESHED = 'AUTH_TOKEN_REFRESHED',
  AUTH_TOKEN_REUSE_DETECTED = 'AUTH_TOKEN_REUSE_DETECTED',
  AUTH_PASSWORD_RESET_REQUESTED = 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_PASSWORD_RESET_COMPLETED = 'AUTH_PASSWORD_RESET_COMPLETED',
  AUTH_EMAIL_VERIFIED = 'AUTH_EMAIL_VERIFIED',

  // Tenant actions
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_UPDATED = 'TENANT_UPDATED',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  TENANT_ACTIVATED = 'TENANT_ACTIVATED',

  // Module actions
  MODULE_ENABLED = 'MODULE_ENABLED',
  MODULE_DISABLED = 'MODULE_DISABLED',

  // User/Collaborator actions
  USER_INVITED = 'USER_INVITED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DISABLED = 'USER_DISABLED',
  USER_ENABLED = 'USER_ENABLED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  SESSIONS_REVOKED = 'SESSIONS_REVOKED',

  // Subscription actions
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  // Abonnements par packs (docs/architecture/PLAN-ABONNEMENTS.md)
  SUBSCRIPTION_ITEM_ADDED = 'SUBSCRIPTION_ITEM_ADDED',
  SUBSCRIPTION_ITEM_REMOVED = 'SUBSCRIPTION_ITEM_REMOVED',
  SUBSCRIPTION_PACK_CHANGED = 'SUBSCRIPTION_PACK_CHANGED',
  SUBSCRIPTION_SETTINGS_UPDATED = 'SUBSCRIPTION_SETTINGS_UPDATED',
  SUBSCRIPTION_MIGRATED_TO_PACKS = 'SUBSCRIPTION_MIGRATED_TO_PACKS',
  CAPACITY_OVERRIDE_GRANTED = 'CAPACITY_OVERRIDE_GRANTED',
  CAPACITY_OVERRIDE_REVOKED = 'CAPACITY_OVERRIDE_REVOKED',
  // Lecture seule manuelle (Baba, 25/09) : hors impaye, posee/levee par le super-admin.
  SUBSCRIPTION_MANUAL_READ_ONLY_SET = 'SUBSCRIPTION_MANUAL_READ_ONLY_SET',
  SUBSCRIPTION_MANUAL_READ_ONLY_CLEARED = 'SUBSCRIPTION_MANUAL_READ_ONLY_CLEARED',
  CATALOG_ITEM_UPDATED = 'CATALOG_ITEM_UPDATED',
  MODULE_OVERRIDE_CLEARED = 'MODULE_OVERRIDE_CLEARED',
  // Vague 3, lot B : element modifie, demandes d'extension, paiement en ligne.
  SUBSCRIPTION_ITEM_UPDATED = 'SUBSCRIPTION_ITEM_UPDATED',
  SUBSCRIPTION_EXTENSION_REQUESTED = 'SUBSCRIPTION_EXTENSION_REQUESTED',
  SUBSCRIPTION_EXTENSION_REQUEST_HANDLED = 'SUBSCRIPTION_EXTENSION_REQUEST_HANDLED',
  PLATFORM_PAYMENT_STARTED = 'PLATFORM_PAYMENT_STARTED',

  // Invoice actions
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_MARKED_PAID = 'INVOICE_MARKED_PAID',
  INVOICE_CANCELED = 'INVOICE_CANCELED',
  // Factures PLATFORM (vague 3, lot A)
  INVOICE_ISSUED = 'INVOICE_ISSUED',
  INVOICE_CREDIT_NOTE_ISSUED = 'INVOICE_CREDIT_NOTE_ISSUED',

  // CRM Calendar actions
  CRM_FOLLOWUP_RESCHEDULED = 'CRM_FOLLOWUP_RESCHEDULED',
  CRM_FOLLOWUP_MARKED_DONE = 'CRM_FOLLOWUP_MARKED_DONE',

  // Property actions
  PROPERTY_CREATED = 'PROPERTY_CREATED',
  PROPERTY_UPDATED = 'PROPERTY_UPDATED',
  PROPERTY_DELETED = 'PROPERTY_DELETED',
  PROPERTY_PUBLISHED = 'PROPERTY_PUBLISHED',
  PROPERTY_UNPUBLISHED = 'PROPERTY_UNPUBLISHED',
  PROPERTY_STATUS_CHANGED = 'PROPERTY_STATUS_CHANGED',
  PROPERTY_MEDIA_UPLOADED = 'PROPERTY_MEDIA_UPLOADED',
  PROPERTY_DOCUMENT_UPLOADED = 'PROPERTY_DOCUMENT_UPLOADED',
  PROPERTY_MANDATE_CREATED = 'PROPERTY_MANDATE_CREATED',
  PROPERTY_MANDATE_REVOKED = 'PROPERTY_MANDATE_REVOKED',
  PROPERTY_VISIT_SCHEDULED = 'PROPERTY_VISIT_SCHEDULED',

  // Syndic - fonds financiers de copropriete (FR-013)
  SYNDICATE_FUND_CREATED = 'SYNDICATE_FUND_CREATED',
  SYNDICATE_FUND_RENAMED = 'SYNDICATE_FUND_RENAMED',
  SYNDICATE_FUND_BALANCE_ADJUSTED = 'SYNDICATE_FUND_BALANCE_ADJUSTED',

  // Syndic - portail coproprietaire (invitation et revocation d'acces)
  SYNDIC_COOWNER_PORTAL_INVITED = 'SYNDIC_COOWNER_PORTAL_INVITED',
  SYNDIC_COOWNER_PORTAL_REVOKED = 'SYNDIC_COOWNER_PORTAL_REVOKED'
}

// Audit log entry
// CRM entity types for audit logging
export const CRM_ENTITY_TYPES = {
  CONTACT: 'CONTACT',
  DEAL: 'DEAL',
  ACTIVITY: 'ACTIVITY'
} as const;

// Property entity types for audit logging
export const PROPERTY_ENTITY_TYPES = {
  PROPERTY: 'PROPERTY',
  PROPERTY_MEDIA: 'PROPERTY_MEDIA',
  PROPERTY_DOCUMENT: 'PROPERTY_DOCUMENT',
  PROPERTY_MANDATE: 'PROPERTY_MANDATE',
  PROPERTY_VISIT: 'PROPERTY_VISIT'
} as const;

export type CrmEntityType = (typeof CRM_ENTITY_TYPES)[keyof typeof CRM_ENTITY_TYPES];

export interface AuditLogEntry {
  actorUserId?: string | null;
  tenantId?: string | null;
  actionKey: AuditActionKey | string;
  entityType: string;
  entityId: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  payload?: Record<string, unknown> | null;
  createdAt?: Date;
}

// Audit log query filters
export interface AuditLogFilters {
  tenantId?: string;
  actionKey?: string;
  entityType?: string;
  entityId?: string;
  actorUserId?: string;
  startDate?: Date;
  endDate?: Date;
  page?: number;
  limit?: number;
}

// Audit log response
export interface AuditLogResponse {
  logs: AuditLogEntry[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}
