// Audit log action keys
export enum AuditActionKey {
  // Authentication actions
  // Login, logout and credential changes were not traced at all, which left no
  // way to investigate a compromised account (see AUDIT_CODE.md 4.8).
  AUTH_LOGIN_SUCCEEDED = 'AUTH_LOGIN_SUCCEEDED',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_GOOGLE_LOGIN = 'AUTH_GOOGLE_LOGIN',
  AUTH_TOKEN_REFRESHED = 'AUTH_TOKEN_REFRESHED',
  AUTH_TOKEN_REUSE_DETECTED = 'AUTH_TOKEN_REUSE_DETECTED',
  AUTH_PASSWORD_RESET_REQUESTED = 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_PASSWORD_RESET_COMPLETED = 'AUTH_PASSWORD_RESET_COMPLETED',
  AUTH_EMAIL_VERIFIED = 'AUTH_EMAIL_VERIFIED',

  // Tenant actions
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_UPDATED = 'TENANT_UPDATED',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  TENANT_ACTIVATED = 'TENANT_ACTIVATED',
  // Lot S7 : export complet des donnees d'une agence (super-admin).
  TENANT_DATA_EXPORT_REQUESTED = 'TENANT_DATA_EXPORT_REQUESTED',
  TENANT_DATA_EXPORT_DOWNLOADED = 'TENANT_DATA_EXPORT_DOWNLOADED',
  TENANT_DATA_EXPORT_DELETED = 'TENANT_DATA_EXPORT_DELETED',

  // Module actions
  MODULE_ENABLED = 'MODULE_ENABLED',
  MODULE_DISABLED = 'MODULE_DISABLED',

  // User/Collaborator actions
  USER_INVITED = 'USER_INVITED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DISABLED = 'USER_DISABLED',
  USER_ENABLED = 'USER_ENABLED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  SESSIONS_REVOKED = 'SESSIONS_REVOKED',

  // Subscription actions
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  // Abonnements par packs (docs/architecture/PLAN-ABONNEMENTS.md)
  SUBSCRIPTION_ITEM_ADDED = 'SUBSCRIPTION_ITEM_ADDED',
  SUBSCRIPTION_ITEM_REMOVED = 'SUBSCRIPTION_ITEM_REMOVED',
  SUBSCRIPTION_PACK_CHANGED = 'SUBSCRIPTION_PACK_CHANGED',
  SUBSCRIPTION_SETTINGS_UPDATED = 'SUBSCRIPTION_SETTINGS_UPDATED',
  SUBSCRIPTION_MIGRATED_TO_PACKS = 'SUBSCRIPTION_MIGRATED_TO_PACKS',
  CAPACITY_OVERRIDE_GRANTED = 'CAPACITY_OVERRIDE_GRANTED',
  CAPACITY_OVERRIDE_REVOKED = 'CAPACITY_OVERRIDE_REVOKED',
  // Lecture seule manuelle (Baba, 25/09) : hors impaye, posee/levee par le super-admin.
  SUBSCRIPTION_MANUAL_READ_ONLY_SET = 'SUBSCRIPTION_MANUAL_READ_ONLY_SET',
  SUBSCRIPTION_MANUAL_READ_ONLY_CLEARED = 'SUBSCRIPTION_MANUAL_READ_ONLY_CLEARED',
  CATALOG_ITEM_UPDATED = 'CATALOG_ITEM_UPDATED',
  MODULE_OVERRIDE_CLEARED = 'MODULE_OVERRIDE_CLEARED',
  // Vague 3, lot B : element modifie, demandes d'extension, paiement en ligne.
  SUBSCRIPTION_ITEM_UPDATED = 'SUBSCRIPTION_ITEM_UPDATED',
  SUBSCRIPTION_EXTENSION_REQUESTED = 'SUBSCRIPTION_EXTENSION_REQUESTED',
  SUBSCRIPTION_EXTENSION_REQUEST_HANDLED = 'SUBSCRIPTION_EXTENSION_REQUEST_HANDLED',
  PLATFORM_PAYMENT_STARTED = 'PLATFORM_PAYMENT_STARTED',

  // Invoice actions
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_MARKED_PAID = 'INVOICE_MARKED_PAID',
  INVOICE_CANCELED = 'INVOICE_CANCELED',
  // Factures PLATFORM (vague 3, lot A)
  INVOICE_ISSUED = 'INVOICE_ISSUED',
  INVOICE_CREDIT_NOTE_ISSUED = 'INVOICE_CREDIT_NOTE_ISSUED',

  // CRM Calendar actions
  CRM_FOLLOWUP_RESCHEDULED = 'CRM_FOLLOWUP_RESCHEDULED',
  CRM_FOLLOWUP_MARKED_DONE = 'CRM_FOLLOWUP_MARKED_DONE',

  // Property actions
  PROPERTY_CREATED = 'PROPERTY_CREATED',
  PROPERTY_UPDATED = 'PROPERTY_UPDATED',
  PROPERTY_DELETED = 'PROPERTY_DELETED',
  PROPERTY_PUBLISHED = 'PROPERTY_PUBLISHED',
  PROPERTY_UNPUBLISHED = 'PROPERTY_UNPUBLISHED',
  PROPERTY_STATUS_CHANGED = 'PROPERTY_STATUS_CHANGED',
  PROPERTY_MEDIA_UPLOADED = 'PROPERTY_MEDIA_UPLOADED',
  PROPERTY_DOCUMENT_UPLOADED = 'PROPERTY_DOCUMENT_UPLOADED',
  PROPERTY_MANDATE_CREATED = 'PROPERTY_MANDATE_CREATED',
  PROPERTY_MANDATE_REVOKED = 'PROPERTY_MANDATE_REVOKED',
  PROPERTY_VISIT_SCHEDULED = 'PROPERTY_VISIT_SCHEDULED',

  // Syndic - fonds financiers de copropriete (FR-013)
  SYNDICATE_FUND_CREATED = 'SYNDICATE_FUND_CREATED',
  SYNDICATE_FUND_RENAMED = 'SYNDICATE_FUND_RENAMED',
  SYNDICATE_FUND_BALANCE_ADJUSTED = 'SYNDICATE_FUND_BALANCE_ADJUSTED',
  // Affectation d'un appel ou d'un poste de budget a un fonds (credit des paiements).
  SYNDICATE_FUND_ASSIGNMENT_CHANGED = 'SYNDICATE_FUND_ASSIGNMENT_CHANGED',
  // Syndic S6 : piece jointe d'une facture de prestataire.
  SYNDIC_PROVIDER_INVOICE_FILE_ATTACHED = 'SYNDIC_PROVIDER_INVOICE_FILE_ATTACHED',
  SYNDIC_PROVIDER_INVOICE_FILE_REPLACED = 'SYNDIC_PROVIDER_INVOICE_FILE_REPLACED',
  SYNDIC_PROVIDER_INVOICE_FILE_REMOVED = 'SYNDIC_PROVIDER_INVOICE_FILE_REMOVED',

  // Syndic - portail coproprietaire (invitation et revocation d'acces)
  SYNDIC_COOWNER_PORTAL_INVITED = 'SYNDIC_COOWNER_PORTAL_INVITED',
  SYNDIC_COOWNER_PORTAL_REVOKED = 'SYNDIC_COOWNER_PORTAL_REVOKED',

  // Identite des documents (lot S1) : signature et cachet d'un mandant ou de l'agence
  DOCUMENT_SIGNATURE_UPLOADED = 'DOCUMENT_SIGNATURE_UPLOADED',
  DOCUMENT_SIGNATURE_REMOVED = 'DOCUMENT_SIGNATURE_REMOVED',

  // Syndic - recus et quittances de charges (lot S3) : renvoi manuel par e-mail
  SYNDIC_CHARGE_RECEIPT_EMAIL_RESENT = 'SYNDIC_CHARGE_RECEIPT_EMAIL_RESENT',

  // Rapport mensuel propriétaire envoyé avec un lien sécurisé (lot A3).
  PATRIMOINE_OWNER_MONTHLY_REPORT_SENT = 'PATRIMOINE_OWNER_MONTHLY_REPORT_SENT',
  // Patrimoine (spec 032) : suivi des sinistres. Les alertes de police et
  // d'entretien ne sont plus des evenements d'audit (marques anti-doublon dans
  // `notification_markers`, voir `lib/notification-markers.ts`).
  PATRIMOINE_INSURANCE_CLAIM_DECLARED = 'PATRIMOINE_INSURANCE_CLAIM_DECLARED',
  PATRIMOINE_INSURANCE_CLAIM_STATUS_CHANGED = 'PATRIMOINE_INSURANCE_CLAIM_STATUS_CHANGED',

  // Patrimoine (lot B2, spec 033) : regularisation fonciere. Payloads sans donnee
  // sensible (from/to, reason, reopened).
  LAND_REGULARIZATION_CREATED = 'LAND_REGULARIZATION_CREATED',
  LAND_REGULARIZATION_STATUS_CHANGED = 'LAND_REGULARIZATION_STATUS_CHANGED',
  LAND_STEP_STATUS_CHANGED = 'LAND_STEP_STATUS_CHANGED',
  LAND_STEP_UPDATED = 'LAND_STEP_UPDATED',

  // Liens sécurisés (lib/secure-links, lot A3) : jamais le jeton ni son hash.
  SECURE_LINK_CREATED = 'SECURE_LINK_CREATED',
  SECURE_LINK_VIEWED = 'SECURE_LINK_VIEWED',
  SECURE_LINK_REVOKED = 'SECURE_LINK_REVOKED',
  /** Lot C5 : le locataire a lancé le paiement depuis son lien (checkout créé ou repris). */
  SECURE_LINK_PAYMENT_STARTED = 'SECURE_LINK_PAYMENT_STARTED',
  /** Lot C5 : lien de paiement d'une échéance envoyé au locataire (canal, jamais le jeton). */
  RENTAL_PAYMENT_LINK_SENT = 'RENTAL_PAYMENT_LINK_SENT',

  // Accès en lecture seule des tiers de confiance (lot B3, spec 034) : jamais le
  // jeton, jamais l'e-mail du bénéficiaire. entityType 'ExternalAccessGrant'.
  EXTERNAL_ACCESS_GRANT_CREATED = 'EXTERNAL_ACCESS_GRANT_CREATED',
  EXTERNAL_ACCESS_GRANT_UPDATED = 'EXTERNAL_ACCESS_GRANT_UPDATED',
  EXTERNAL_ACCESS_GRANT_REVOKED = 'EXTERNAL_ACCESS_GRANT_REVOKED',
  EXTERNAL_ACCESS_GRANT_LINK_SENT = 'EXTERNAL_ACCESS_GRANT_LINK_SENT',
  EXTERNAL_ACCESS_GRANT_VIEWED = 'EXTERNAL_ACCESS_GRANT_VIEWED',
  EXTERNAL_ACCESS_GRANT_DOCUMENT_DOWNLOADED = 'EXTERNAL_ACCESS_GRANT_DOCUMENT_DOWNLOADED',

  // ImmoCopilot (docs/architecture/PLAN_IMMOCOPILOT.md) : assistant IA.
  AI_CHAT_TURN = 'AI_CHAT_TURN',
  AI_TOOL_CALLED = 'AI_TOOL_CALLED',
  AI_TOOL_DENIED = 'AI_TOOL_DENIED',
  AI_PROPOSAL_ISSUED = 'AI_PROPOSAL_ISSUED',
  AI_PROPOSAL_REDEEMED = 'AI_PROPOSAL_REDEEMED',
  AI_ACTION_EXECUTED = 'AI_ACTION_EXECUTED',
  AI_ACTION_REJECTED = 'AI_ACTION_REJECTED',

  // Réglage ImmoCopilot de la plateforme (super-admin) : jamais de secret dans le payload.
  AI_SETTINGS_UPDATED = 'AI_SETTINGS_UPDATED',

  // CRM (clés historiques, longtemps passées en chaîne libre)
  CRM_ACTIVITY_CREATED = 'CRM_ACTIVITY_CREATED',
  CRM_CONTACT_CREATED = 'CRM_CONTACT_CREATED',
  CRM_CONTACT_UPDATED = 'CRM_CONTACT_UPDATED',
  CRM_CONTACT_DELETED = 'CRM_CONTACT_DELETED',
  CRM_CONTACT_CONVERTED = 'CRM_CONTACT_CONVERTED',
  CRM_CONTACT_ROLES_UPDATED = 'CRM_CONTACT_ROLES_UPDATED',
  CRM_CONTACT_ROLE_DELETED = 'CRM_CONTACT_ROLE_DELETED',
  CRM_DEAL_CREATED = 'CRM_DEAL_CREATED',
  CRM_DEAL_UPDATED = 'CRM_DEAL_UPDATED',
  CRM_DEAL_STAGE_CHANGED = 'CRM_DEAL_STAGE_CHANGED',

  // Documents
  DOCUMENT_GENERATED = 'DOCUMENT_GENERATED',
  DOCUMENT_REGENERATED = 'DOCUMENT_REGENERATED',
  DOCUMENT_TEMPLATE_UPLOADED = 'DOCUMENT_TEMPLATE_UPLOADED',
  DOCUMENT_TEMPLATE_ACTIVATED = 'DOCUMENT_TEMPLATE_ACTIVATED',
  DOCUMENT_TEMPLATE_DEACTIVATED = 'DOCUMENT_TEMPLATE_DEACTIVATED',
  DOCUMENT_TEMPLATE_SET_DEFAULT = 'DOCUMENT_TEMPLATE_SET_DEFAULT',
  DOCUMENT_TEMPLATE_DELETED = 'DOCUMENT_TEMPLATE_DELETED',

  // Maintenance
  MAINTENANCE_TICKET_CREATED = 'MAINTENANCE_TICKET_CREATED',
  MAINTENANCE_VENDOR_CREATED = 'MAINTENANCE_VENDOR_CREATED',
  MAINTENANCE_VENDOR_UPDATED = 'MAINTENANCE_VENDOR_UPDATED',
  MAINTENANCE_VENDOR_DEACTIVATED = 'MAINTENANCE_VENDOR_DEACTIVATED',
  MAINTENANCE_VENDOR_DELETED = 'MAINTENANCE_VENDOR_DELETED',

  // Location
  RENTAL_LEASE_CREATED = 'RENTAL_LEASE_CREATED',
  RENTAL_LEASE_UPDATED = 'RENTAL_LEASE_UPDATED',
  RENTAL_LEASE_STATUS_UPDATED = 'RENTAL_LEASE_STATUS_UPDATED',
  RENTAL_LEASE_DELETED = 'RENTAL_LEASE_DELETED',
  RENTAL_LEASE_CO_RENTER_ADDED = 'RENTAL_LEASE_CO_RENTER_ADDED',
  RENTAL_LEASE_CO_RENTER_REMOVED = 'RENTAL_LEASE_CO_RENTER_REMOVED',
  RENTAL_LEASE_RENT_REVISED = 'RENTAL_LEASE_RENT_REVISED',
  RENTAL_LEASE_RENEWED = 'RENTAL_LEASE_RENEWED',
  RENTAL_LEASE_AMENDED = 'RENTAL_LEASE_AMENDED',
  RENTAL_LEASE_TERMINATED = 'RENTAL_LEASE_TERMINATED',
  RENTAL_DOCUMENT_GENERATED = 'RENTAL_DOCUMENT_GENERATED',
  RENTAL_DOCUMENT_STATUS_UPDATED = 'RENTAL_DOCUMENT_STATUS_UPDATED',
  RENTAL_DEPOSIT_CREATED = 'RENTAL_DEPOSIT_CREATED',
  RENTAL_DEPOSIT_MOVEMENT_CREATED = 'RENTAL_DEPOSIT_MOVEMENT_CREATED',
  RENTAL_INSTALLMENT_MARKED_OVERDUE = 'RENTAL_INSTALLMENT_MARKED_OVERDUE',
  RENTAL_PENALTY_CALCULATED = 'RENTAL_PENALTY_CALCULATED',
  RENTAL_PENALTY_UPDATED = 'RENTAL_PENALTY_UPDATED',
  RENTAL_PENALTY_DELETED = 'RENTAL_PENALTY_DELETED',
  RENTAL_PENALTY_JUSTIFICATION_UPLOADED = 'RENTAL_PENALTY_JUSTIFICATION_UPLOADED',

  // Divers
  LOT_REGISTRY_RECONCILED = 'LOT_REGISTRY_RECONCILED',
  PATRIMOINE_WORK_PROGRAM_COST_OVERRIDDEN = 'PATRIMOINE_WORK_PROGRAM_COST_OVERRIDDEN',
  SUBSCRIPTION_PROVISIONED = 'SUBSCRIPTION_PROVISIONED',
  TENANT_PROVISIONED = 'TENANT_PROVISIONED',

  // Audit de l'audit (ADR-006) : consulter le journal est lui-même tracé.
  AUDIT_VIEWED = 'AUDIT_VIEWED',
  AUDIT_EXPORTED = 'AUDIT_EXPORTED',

  // Maintenance du journal (phase 5) : scellement quotidien et purge de retention.
  AUDIT_SEALED = 'AUDIT_SEALED',
  AUDIT_PURGED = 'AUDIT_PURGED',
  AUDIT_INTEGRITY_FAILED = 'AUDIT_INTEGRITY_FAILED',

  // Accès (phase 3), posés par `middleware/audit-access-middleware.ts` à partir
  // de la réponse : un refus de droit, un fichier ou un export servi.
  ACCESS_DENIED = 'ACCESS_DENIED',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  DOCUMENT_DOWNLOADED = 'DOCUMENT_DOWNLOADED',
  DATA_EXPORTED = 'DATA_EXPORTED'
}

// Audit log entry
// CRM entity types for audit logging
export const CRM_ENTITY_TYPES = {
  CONTACT: 'CONTACT',
  DEAL: 'DEAL',
  ACTIVITY: 'ACTIVITY'
} as const;

// Property entity types for audit logging
export const PROPERTY_ENTITY_TYPES = {
  PROPERTY: 'PROPERTY',
  PROPERTY_MEDIA: 'PROPERTY_MEDIA',
  PROPERTY_DOCUMENT: 'PROPERTY_DOCUMENT',
  PROPERTY_MANDATE: 'PROPERTY_MANDATE',
  PROPERTY_VISIT: 'PROPERTY_VISIT'
} as const;

export type CrmEntityType = (typeof CRM_ENTITY_TYPES)[keyof typeof CRM_ENTITY_TYPES];

// Valeurs des enumerations Prisma (AuditScope, ...), redeclarees ici pour que ce
// module reste importable dans les tests qui remplacent `@prisma/client` par un
// mock sans enumerations.
export type AuditScopeValue = 'TENANT' | 'PLATFORM';
export type AuditVisibilityValue = 'TENANT' | 'PLATFORM_ONLY';
export type AuditCategoryValue = 'AUTH' | 'DATA' | 'ADMIN' | 'SECURITY' | 'BILLING' | 'EXPORT' | 'AI' | 'SYSTEM';
export type AuditOutcomeValue = 'SUCCESS' | 'FAILURE' | 'DENIED';
export type AuditActorTypeValue = 'USER' | 'SUPER_ADMIN' | 'PORTAL' | 'SYSTEM' | 'AI';

/**
 * Entree de journal telle que l'ecrit un appelant. Tout ce qui est facultatif
 * est complete automatiquement (contexte de requete, catalogue) ; une valeur
 * fournie par l'appelant l'emporte toujours.
 */
export interface AuditLogEntry {
  actorUserId?: string | null;
  tenantId?: string | null;
  actionKey: AuditActionKey | string;
  entityType: string;
  entityId: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  payload?: Record<string, unknown> | null;
  createdAt?: Date;
  scope?: AuditScopeValue;
  visibility?: AuditVisibilityValue;
  category?: AuditCategoryValue;
  outcome?: AuditOutcomeValue;
  actorType?: AuditActorTypeValue;
  actorLabel?: string | null;
  requestId?: string | null;
  source?: string | null;
  /** Champs modifies : { champ: { before, after } }. Secrets masques a l'ecriture. */
  changes?: Record<string, unknown> | null;
}
